select case slotNumber
case ITEM_BIGOSCILLOSCOPE_SLOT_PLAYSOUNDTEST_E
    BIGOSCILLOSCOPE_SLOT_PLAYSOUNDTEST(pvPair())
case ITEM_BIGOSCILLOSCOPE_SLOT_DRAW2PARAMS_E
    BIGOSCILLOSCOPE_SLOT_DRAW2PARAMS(pvPair())
case ITEM_FREQUENCYCOUNTER_SLOT_TESTSLOT3_E
    FREQUENCYCOUNTER_SLOT_TESTSLOT3(pvPair())
case ITEM_FREQUENCYCOUNTER_SLOT_EXPLODE_E
    FREQUENCYCOUNTER_SLOT_EXPLODE(pvPair())
case ITEM_TANDY2000_SLOT_MYONLYSLOT_E
    TANDY2000_SLOT_MYONLYSLOT(pvPair())
end select
