select case slotNumber
case ITEM_ALIENSPINNER_SLOT_INTERACT_E
    ALIENSPINNER_SLOT_INTERACT(pvPair())
case ITEM_ANTIPERSONNELMINE_SLOT_EXPLODE_E
    ANTIPERSONNELMINE_SLOT_EXPLODE(pvPair())
case ITEM_BALLSPAWNER_SLOT_SPAWN_E
    BALLSPAWNER_SLOT_SPAWN(pvPair())
case ITEM_BIGOSCILLOSCOPE_SLOT_INTERACT_E
    BIGOSCILLOSCOPE_SLOT_INTERACT(pvPair())
case ITEM_DEEPSPOTLIGHT_SLOT_ENABLE_E
    DEEPSPOTLIGHT_SLOT_ENABLE(pvPair())
case ITEM_ELECTRICMINE_SLOT_EXPLODE_E
    ELECTRICMINE_SLOT_EXPLODE(pvPair())
case ITEM_ENERGYBALL_SLOT_REACT_E
    ENERGYBALL_SLOT_REACT(pvPair())
case ITEM_FREIGHTELEVATOR_SLOT_INTERACT_E
    FREIGHTELEVATOR_SLOT_INTERACT(pvPair())
case ITEM_FREQUENCYCOUNTER_SLOT_INTERACT_E
    FREQUENCYCOUNTER_SLOT_INTERACT(pvPair())
case ITEM_INTERFACE_SLOT_INTERACT_E
    INTERFACE_SLOT_INTERACT(pvPair())
case ITEM_MOMENTARYTOGGLESWITCH_SLOT_INTERACT_E
    MOMENTARYTOGGLESWITCH_SLOT_INTERACT(pvPair())
case ITEM_PUZZLETUBE1_SLOT_ACTIVATE_E
    PUZZLETUBE1_SLOT_ACTIVATE(pvPair())
case ITEM_PUZZLETUBE1_SLOT_RESET_E
    PUZZLETUBE1_SLOT_RESET(pvPair())
case ITEM_PUZZLETUBE1_SLOT_LOCKUP_E
    PUZZLETUBE1_SLOT_LOCKUP(pvPair())
case ITEM_PUZZLETUBE1_SLOT_SETUP_E
    PUZZLETUBE1_SLOT_SETUP(pvPair())
case ITEM_PUZZLE1234_SLOT_RESET_E
    PUZZLE1234_SLOT_RESET(pvPair())
case ITEM_PUZZLE1234_SLOT_CYCLE_E
    PUZZLE1234_SLOT_CYCLE(pvPair())
case ITEM_SHOCKTARGET1_SLOT_SHOCKTARGET_E
    SHOCKTARGET1_SLOT_SHOCKTARGET(pvPair())
case ITEM_SMALLOSCILLOSCOPE_SLOT_INTERACT_E
    SMALLOSCILLOSCOPE_SLOT_INTERACT(pvPair())
case ITEM_SMOKEMINE_SLOT_EXPLODE_E
    SMOKEMINE_SLOT_EXPLODE(pvPair())
case ITEM_STANDUPSWITCH_SLOT_INTERACT_E
    STANDUPSWITCH_SLOT_INTERACT(pvPair())
case ITEM_TANDY2000_SLOT_INTERACT_E
    TANDY2000_SLOT_INTERACT(pvPair())
case ITEM_TELEPORTERREVEALSEQUENCE_SLOT_START_E
    TELEPORTERREVEALSEQUENCE_SLOT_START(pvPair())
case ITEM_TELEPORTERSWITCH_SLOT_INTERACT_E
    TELEPORTERSWITCH_SLOT_INTERACT(pvPair())
case ITEM_TELEPORTERSWITCH_SLOT_ENABLE_E
    TELEPORTERSWITCH_SLOT_ENABLE(pvPair())
case ITEM_TUBEPUZZLEMAP_SLOT_UPDATE_E
    TUBEPUZZLEMAP_SLOT_UPDATE(pvPair())
end select
