select case itemType
case ITEM_BIGOSCILLOSCOPE
    BIGOSCILLOSCOPE_PROC_DRAWOVERLAY(scnbuff)
case ITEM_FREQUENCYCOUNTER
    FREQUENCYCOUNTER_PROC_DRAWOVERLAY(scnbuff)
case ITEM_TANDY2000
    TANDY2000_PROC_DRAWOVERLAY(scnbuff)
end select
